clear
parameters = struct(...
    'beta', 0.6, ...
    'gamma', 2.7268, ...
    'alpha', 0.25, ...
    'A_hat', 2.108, ...
    'A_tilde', .0002, ...
    'mu', 0, ...
    'theta', 1, ...
    'eta', inf, ...
    'sigma',5, ...
    'r_b', 0.05, ...
    'green_premium', 0, ...
    'w', 0.500, ... % MSEK
    'tau_E', 0, ... % per ton
    'n', 1000, ...
    'sd_hat', 0.45, ...
    'sd_tilde', 2, ...
    'rho', 0.9 ...
);
clc
obj = functionsContainer();

res_table = obj.simulate_firms_table(parameters);
res_table("intensity","mean")

x0 = [1.2,0.0001,1];
r = @(b) function_test(obj,parameters,b(1),b(2),b(3));
S = fsolve(r,x0)
%%
res = obj.simulate_firms(parameters);
obj.function_coef(parameters,100)*100


%%
function dif = function_test(obj,parameters,gamma,A_tilde,A_hat)
    parameters.gamma = gamma;
    parameters.A_hat = A_hat;
    parameters.A_tilde = A_tilde;
    res_table = obj.simulate_firms_table(parameters);
    dif = [
        table2array(res_table("z_k","mean")) - .05;
        table2array(res_table("intensity","mean")) - .02;
        table2array(res_table("l","mean")) - 250;
        ];
end

